### ISSUE TITLE
How to get the technical corpus

### ISSUE THREAD

**Issue by HancCui** [wyu97/TTQA#1]
When I open your link to download the corpus, it jumped to the google drive page. The name is TTQA-TechCorpus, but the dir
is empty. So how can I get the corpus? Or if it's not convenient to put the corpus into the cloud, could please send it to my email or share a private link? Thanks a lot.

**Comment by ngoquanghuy99** [comment]
I've got this issue also. Could you please send that corpus or grant me permission of accessing the corpus via email?
My email: ngoquanghuy1999lp@gmail.com
Thanks much!

**Comment by wyu97** [comment]
Sorry for the late reply. I may forget to upload the corpus to the google drive. Now you can access the corpus by using this [link](https://drive.google.com/drive/folders/1WCwIIuEzhy695gkmkmIjhlDFxrKOBE0J). Please let me know you have have any other questions.
